[package]
name = "serve_installer"
version = "0.1.0"
edition = "2021"
build = "build.rs"


[dependencies]
winreg = "0.55"
dirs = "6.0"
native-windows-gui = "1.0"

[package.metadata.windows.manifest]
path = "app.manifest"
